name: Manually Deploy to aasath

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: a6addc92-17a0-4586-9bb1-94e0bf387bf2
          heroku_app_name: aasath-vpn22
          heroku_email: aashath-vpn2@c2ptech.com
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
        env:
          HD_CONFIG_FILE_URL: ${{secrets.PASSWORD}}
